<?php if ($member_products || $member_future_products): ?>
<ul id="member-subscriptions">
    <?php foreach ($member_products as $p):  ?>
    <li><strong><?php echo $p->getTitle(); ?></strong> -
    <?php if ($products_expire[$p->pk()] == Am_Period::MAX_SQL_DATE): ?>
        <?php __e('Lifetime') ?>
    <?php else: ?>
        <?php __e('expires') ?> <?php echo amDate($products_expire[$p->pk()]); ?>
    <?php endif ?></li>
    <?php endforeach ?>
    <?php foreach ($member_future_products as $p) : ?>
    <li><?php echo $p->getTitle(); ?> -
        <?php __e('begins') ?> <?php echo amDate($products_begin[$p->pk()]); ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php else : // Customer doesn't have any active subscriptions ?>
    <h3><?php __e('You have no active subscriptions') ?></h3>
    <p><?php __e('Please use %sAdd/Renew subscription%s form', '<a href="' . REL_ROOT_URL . '/signup">','</a>') ?>
    <?php __e('to order or renew subscription.') ?></p>
<?php endif ?>
