<?php $product_url = $product->path ? REL_ROOT_URL . '/product/' . urlencode($product->path) : Am_Controller::makeUrl(null, 'product', null, 'id', $product->pk(), 'c', $this->cc); ?>
<div id="am-cart-product-<?php p($product->product_id) ?>" class="am-cart-product<?php echo (empty($displayProductDetails) && $di->config->get('cart.layout') == 1) ? ' am-cart-product-two-column' : '' ?>">
    <div class="am-cart-product-content<?php if (!empty($displayProductDetails)) echo ' am-cart-product-content-details'; ?>">
        <div class="am-cart-product-content-title">
           <?php if (empty($displayProductDetails)) : ?>
                <a href="<?php p($product_url) ?>"><?php p($product->title) ?></a>
           <?php else : ?>
                <h2><?php p($product->title) ?></h2>
           <?php endif; ?>
           <div class="am-cart-product-content-terms">
           <?php
           $plans = $product->getBillingPlans(true);
           if (count($plans)==1) {
               echo $product->getBillingPlan()->getTerms();
           } else {
               $options = array();
               foreach ($plans as $plan)
                    $options[$plan->pk()] = $plan->getTerms();
               echo "<select class='billing-plan-select' name='plan[{$product->product_id}]' size='1'>\n"
               . Am_Controller::renderOptions($options, $product->default_billing_plan_id)
               . "</select>\n";
           }
           ?>
           </div>
        </div>
        <div class="am-cart-product-content-desc">
            <?php if($product->img): ?>
            <div class="am-cart-product-content-desc-img-wrapper">
                <?php if (!empty($displayProductDetails) && $product->img_detail_path) : ?>
                <img class="am-cart-product-content-desc-img"
                      src="<?php echo REL_ROOT_URL ?>/data/public/<?php p($product->img_detail_path) ?>"
                      alt="<?php p($product->title) ?>"
                      title="<?php p($product->title) ?>" />
                <?php else: ?>
                <a href="<?php p($product_url) ?>"><img class="am-cart-product-content-desc-img"
                      src="<?php echo REL_ROOT_URL ?>/data/public/<?php p($product->img_path) ?>"
                      alt="<?php p($product->title) ?>"
                      title="<?php p($product->title) ?>" /></a>
                <?php endif; ?>
            </div>
            <?php endif ?>
            <?php if(empty($displayProductDetails)) : ?>
                <div class="am-cart-product-content-desc-short">
                <?php echo $product->getDescription(false); ?>
                </div>
            <?php else: ?>
                <div class="am-cart-product-content-desc-full">
                <?php echo $product->cart_description ? $product->cart_description : $product->getDescription(false) ?>
                </div>
            <?php endif; ?>
        </div>
        <div class="am-cart-product-status">
            <?php $item = $this->cart->getItem($product) ?>
            <?php include $this->_script('cart/_product_status.phtml') ?>
        </div>
        <div class="am-cart-product-content-buttons">
            <input class="am-cart-button-add" type="button" name="add" value="<?php __e('Add to Basket')?>" onclick="cart.add(this,<?php echo $product->product_id; ?>, 1)">
            <input class="am-cart-button-order" type="button" name="order" value="<?php __e('Quick Order')?>" onclick="cart.addAndCheckout(this,<?php echo $product->product_id; ?>); ">
        </div>
    </div>
</div>