<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,400italic,300,600,600italic,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
<style type="text/css">
@charset "utf-8";
/* CSS Document */
html {
	background-color:#2E5C94;
!important;
}
body {
	padding:0;
	margin:0;
	background:#2e5c94;
}
.login-frm-area {
	width:729px;
	margin:0 auto;
	border-radius:10px;
	background:#fff url(/serp_avenger/amember/images/login-bx-bg.png) no-repeat;
	margin-top:100px;
}
.login-frm-main {
	width:354px;
	margin:0 auto;
	padding-bottom: 25px;
}
.login-frm-area span.logo {
	text-align:center;
	display:block;
	padding:15px 0;
}
.login-frm-main span.frm-heading {
	font-family: 'Roboto Condensed', sans-serif;
	font-size:26px;
	font-weight:bold;
	text-align:center;
	display:block;
	text-transform:uppercase;
	color:#2f5f98;
	padding-top: 20px;
}
.login-bx-fld p {
	margin:0;
	padding-bottom:23px;
}
.login-bx-fld p input {
	-webkit-border-radius: 5px;
	-moz-border-radius: 5px;
	border-radius: 5px;
	-webkit-box-shadow: inset 1px 2px 2px rgba(0, 0, 0, .05);
	-moz-box-shadow: inset 1px 2px 2px rgba(0, 0, 0, .05);
	box-shadow: inset 1px 2px 2px rgba(0, 0, 0, .05);
	border: solid 1px #ddd;
	width:82%;
	background:url(/serp_avenger/amember/images/login-bx-fld-icon.png) no-repeat;
	padding:10px 11px 9px 49px;
	color:#333333;
	font-family: 'Open Sans', sans-serif;
	font-size:14px;
}


::-webkit-input-placeholder {
 color:    #000;
}
:-moz-placeholder {
 color:    #000;
}
::-moz-placeholder {
 color:    #000;
}
:-ms-input-placeholder {
 color:    #000;
}
.login-bx-fld p input.psssfld {
	background-position:0 bottom;
}
.btn-login {
	height: 32px !important;
	-webkit-border-radius: 5px !important;
	-moz-border-radius: 5px !important;
	border-radius: 5px !important;
	background-color: #000 !important;
	-webkit-box-shadow: inset 1px 1px #fff !important;
	-moz-box-shadow: inset 1px 1px #fff !important;
	box-shadow: inset 1px 1px #fff !important;
	background-image: -webkit-linear-gradient(bottom, #ec7100, #e69702) !important;
	background-image: -moz-linear-gradient(bottom, #ec7100, #e69702) !important;
	background-image: -o-linear-gradient(bottom, #ec7100, #e69702) !important;
	background-image: linear-gradient(to top, #ec7100, #e69702) !important;
	border:0 !important;
	font-family: 'Open Sans', sans-serif !important;
	font-size:16px !important;
	color:#fff !important;
	text-shadow: 1px 2px 2px rgba(0, 0, 0, .1) !important;
	text-transform:uppercase !important;
	cursor:pointer !important;
}
.login-frm-main span.lgn-btn {
	display:block;
	text-align:center;
}
.login-frm-main ul {
	padding:0;
	margin:0;
	list-style-type:none;
}
.login-frm-main ul li {
	text-align:center;
	color:#999999;
	font-family: 'Open Sans', sans-serif;
	font-size:14px;
	padding-top:10px;
}
.login-frm-main ul li.signup a {
	color:#287dc6;
}
.login-frm-main ul li.forgot-pass a:hover, .login-frm-main ul li.signup a:hover {
	text-decoration:none;
}
.login-frm-main ul li.forgot-pass a {
	color:#fa9235;
	font-style:italic;
}
div.errors ul, ul.error, ul.errors {
    background: none repeat scroll 0 0 rgba(0, 0, 0, 0) !important;
    border-radius: 10px;
    color: #ba2727 !important;
    margin: 0 0 1em;
    padding: 0;
}
.login-frm-main ul li {color: #ba2727 !important;}
</style>

<div class="login-frm-area">
    	<div class="login-frm-main">
        	<span class="logo">
            	<img src="/serp_avenger/amember/images/login-logo.png" width="217" height="88" alt=""/>
            </span>
		<?php if(isset($_REQUEST['forgot_password']) && $_REQUEST['forgot_password'] =='true') { ?>
        <span class="frm-heading">Lost Password?</span> <?php include $this->_script('_error.phtml'); ?><br />
        <form name="sendpass" method="post" action="<?php echo REL_ROOT_URL ?>/sendpass">
            <div class="login-bx-fld">
            	<p><input type="text" name="login" id="sendpass" placeholder="<?php __e('Enter your E-Mail Address or Username') ?>"></p>
            </div>
            <span class="lgn-btn"><input class="btn-login" type="submit" value="<?php __e('Get Password') ?>"></span>
            </form>
        <?php }else{?>
         <span class="frm-heading">Login</span>
         <?php if(isset($_REQUEST['stat']) && $_REQUEST['stat'] == 1) { ?>
          <div style="padding-bottom:10px">
          <p>Thank you for your payment. Your transaction has been completed.<br>
          An email containing your username and password has already been sent to your paypal email address</p>
          </div>
 <?php } ?>     
            <?php include $this->_script('_error.phtml'); ?><br />
               <form name="login" method="post" <?php if ($form_action) echo "action='$form_action'"; ?>>
            <div class="login-bx-fld">
            	<p><input type="text"  id="login" name="amember_login" value="<?php p(@$_REQUEST['amember_login']) ?>" autofocus="autofocus" placeholder="Username"></p>
                <p><input class="psssfld" type="password" id="pass" name="amember_pass" placeholder="Password"></p>
            </div><?php echo Am_Controller::renderArrayAsInputHiddens($hidden) ?>
            <span class="lgn-btn"><input class="btn-login" type="submit" value="login"></span>
            </form>
            <ul>
            	<li class="signup"><?php __e('Not registered yet?') ?> <a href="<?php echo REL_ROOT_URL ?>/signup<?php p(isset($hidden['saved_form']) ? '/' . $hidden['saved_form'] : '') ?>"><?php __e('Signup here') ?></a></li>
                <li class="forgot-pass"><a href="<?php echo REL_ROOT_URL ?>/login?forgot_password=true">Forgot Password ?</a></li>
            </ul>
            <?php }?>
        </div>
</div>
