<?php
/**
 * This file is included into amember/thanks.html and cc/cc_info.html
 * for displaying of payment receipt information
 */
?>
<div class="am-receipt">
    <div class="am-receipt-content">
        <table class="am-receipt-table">
            <thead>
                <tr class="am-receipt-row-head">
                    <th class="am-receipt-product"><?php __e('Subscription/Product Title') ?></th>
                    <th class="am-receipt-qty"><?php __e('Qty') ?></th>
                    <th class="am-receipt-unit-price"><?php __e('Unit Price') ?></th>
                    <th class="am-receipt-price"><?php __e('Price') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($invoice->getItems() as $p): ?>
                <tr>
                    <td><?php p($p->item_title)?></td>
                    <td class="am-receipt-qty">
                        <?php p($p->qty) ?>
                    </td>
                    <td class="am-receipt-unit-price">
                        <?php p($invoice->getCurrency($p->first_price)) ?>
                    </td>
                    <td class="am-receipt-price">
                            <?php if ($invoice->first_discount > 0): ?>
                        <span class="am-receipt-discounted-price"><?php echo $invoice->getCurrency($p->getFirstSubtotal())?></span>
                            <?php endif ?>
                            <?php echo $invoice->getCurrency($p->getFirstTotal()) ?>
                    </td>
                </tr>
                <?php endforeach ?>
                <tr class="am-receipt-row-delimiter">
                    <td colspan="5"></td>
                </tr>
                <tr>
                    <td class="am-receipt-indent"></td>
                    <td class="am-receipt-total" colspan="2"><strong><?php __e('Subtotal') ?></strong></td>
                    <td class="am-receipt-total am-receipt-price">
                        <?php if ($invoice->first_discount > 0): ?>
                            <span class="am-receipt-discounted-price"><?php
                            echo $invoice->getCurrency($invoice->first_subtotal)?></span>
                            <strong><?php echo $invoice->getCurrency($invoice->first_subtotal-$invoice->first_discount)?></strong>
                        <?php else : ?>
                            <strong><?php echo $invoice->getCurrency($invoice->first_subtotal) ?></strong>
                        <?php endif ?>
                    </td>
                </tr>
                <?php if ($invoice->first_shipping > 0): ?>
                <tr>
                    <td class="am-receipt-indent"></td>
                    <td colspan="2"><?php __e('Shipping') ?></td>
                    <td class="am-receipt-price"><?php echo $invoice->getCurrency($invoice->first_shipping)?></td>
                </tr>
                <?php endif ?>
                <?php if ($invoice->first_tax > 0): ?>
                <tr>
                    <td class="am-receipt-indent"></td>
                    <td colspan="2"><strong><?php __e('Tax Amount') ?></strong></td>
                    <td class="am-receipt-price"><strong><?php echo $invoice->getCurrency($invoice->first_tax)?></strong></td>
                </tr>
                <?php endif ?>
                <tr class="am-receipt-row-total">
                    <td class="am-receipt-indent"></td>
                    <td class="am-receipt-total" colspan="2"><strong><?php __e('Total') ?></strong></td>
                    <td class="am-receipt-total am-receipt-price"><strong><?php echo $invoice->getCurrency($invoice->first_total)?></strong></td>
                </tr>
                <tr class="am-receipt-row-terms">
                    <td colspan="5" class="am-receipt-terms">
                        <strong><?php __e('Subscription Terms')?></strong>:
                        <i><?php p(___($invoice->getTerms())); ?></i>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>