<?php $title = ___('Please login');?>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title><?php p(isset($meta_title) ? $meta_title : $title) ?></title>
        
    </head>
    <body>
        
                    <?php include $this->_script('_content.phtml'); ?>
               
    </body>
</html>
<?php $noInitAjaxForm = true; ?>
<?php include $this->_script('_login.phtml'); ?>

