<?php $title = ___('Processing your Transaction'); $this->setLayout('layout.phtml'); ?>
<div>
    <form id="payment-system-redirect" method="post" action="<?php p($url); ?>" target="_top">
        <noscript>
            <h2><?php __e('Click button to continue') ?></h2>
        </noscript>
        <input type="submit" value="<?php __e('Continue')?>" />
        <?php if (!empty($vars)) echo Am_Controller::renderArrayAsInputHiddens($vars); ?>
    </form>
    <script type="text/javascript">
        document.getElementById('payment-system-redirect').submit();
    </script>
</div>