<?php
$title = $catActive ? $catActive : ___('Affiliate info');
$this->headLink()->appendStylesheet($this->_scriptCss('aff.css'));
$this->setLayout('member/layout.phtml');
/* @var $di Am_Di */
?>
<?php echo $this->blocks('aff/top') ?>
<?php echo $this->blocks('aff/links/top') ?>
<?php if (!$catActive) : ?>
    <?php echo $intro; ?>
    <h2><?php __e('Your General Affiliate Link') ?></h2>
    <div class="am-aff-banner-preview">
        <?php echo $this->formText('', $generalLink, array('class' => 'el-wide')) ?>
    </div>
    <?php if ($canUseCustomRedirect) : ?>
    <?php include $this->_script('aff/_custom-redirect.phtml'); ?>
    <?php endif; ?>
    
<?php endif; ?>
<?php if (count($category) && !(count($category)==1 && $catActive)) : ?>
    <div class="am-block">
        <ul>
        <?php foreach ($category as $cat) : ?>
            <?php if ($cat == $catActive) : ?>
                    <li><h2><?php p($cat) ?></h2></li>
            <?php else: ?>
                <li><h2><a href="<?php echo $this->url(array(
                    'module' => 'aff',
                    'controller' => 'aff',
                    'action' => 'index',
                    'c' => $cat
                ), 'default', true) ?>"><?php p($cat) ?></a></h2></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
<!-- aff banners -->
<?php if (count($affBanners)) : ?>
<h2><?php __e('Banners and Links') ?></h2>
    <?php foreach ($affBanners as $banner) : ?>
    <?php $bannerRenderer = Am_BannerRenderer::create($banner); ?>
    <div class="am-aff-banner-preview">
        <div>
            <div class="am-aff-banner-preview-preview">
                <div class="am-aff-banner-preview-preview-conteiner">
                <?php echo $bannerRenderer->getPreview(); ?>
                </div>
            </div>
            <div class="am-aff-banner-preview-info">
                <div class="am-aff-banner-preview-info-conteiner">
                    <dl class="am-aff-banner-preview-info-details">
                        <dt><?php __e('Title') ?></dt>
                        <dd><?php echo $this->escape($banner->title) ?></dd>
                        <dt><?php __e('Target URL') ?></dt>
                        <dd><a href="<?php echo $banner->url ?>"><?php echo $this->escape($banner->url) ?></a></dd>
                        <?php if ($banner->desc) : ?>
                        <dt><?php __e('Description') ?></dt>
                        <dd><?php echo $this->escape($banner->desc) ?></dd>
                        <?php endif; ?>
                    </dl>
                    <?php if ($note = $bannerRenderer->getNote()) : ?>
                        <a href="javascript:;" onclick="jQuery(this).siblings('.am-aff-banner-note').toggle()" class="local-link"><?php __e('Installation Instructions') ?></a><br />
                        <div class="am-aff-banner-note" style="display:none">
                            <?php echo $note ?>
                        </div>
                    <?php endif; ?>
                    <a href="javascript:;" onclick="jQuery(this).siblings('textarea').toggle()" class="local-link"><?php __e('Source Code &mdash; Copy/Paste Into Your Website') ?></a><br />
                    <textarea class="el-wide" style="display:none; margin-top: 1em;" rows="8"><?php echo $this->escape($bannerRenderer->getPreview()); ?></textarea>
                </div>
            </div>
        </div>
    </div>
    <?php endforeach; ?>
<?php endif; ?>
<!-- aff downloads -->
<?php if (count($affDownloads)) : ?>
<h2><?php __e('Marketing Materials') ?></h2>
<ul class="am-list am-aff-mm">
    <?php foreach ($affDownloads as $download) : ?>
    <li class="am-aff-mm-item"><a href="<?php echo ROOT_URL . '/file/download/path/' . $download->getPath() ?>"><?php echo $this->escape($download->getName()) ?></a>
            <?php if ($download->desc) : ?>
                <em class="am-aff-mm-item-desc"><?php __e($download->desc) ?></em>
            <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<?php echo $this->blocks('aff/links/bottom') ?>