<script type="text/javascript">
jQuery(document).ready(function($) {
    $('.am-tabs li:has(ul) > a').prepend(
        $('<span></span>').addClass('arrow')
    );
    $('.am-tabs .has-children > ul').bind('mouseenter mouseleave', function(){
        $(this).closest('li').toggleClass('active expanded');
    });
            
});
</script>
<div class="am-tabs-wrapper">
<?php
$m = new Am_View_Helper_Menu();
$m->setView($this);

echo $m->renderMenu($this->di->navigationUser,
    array(
        'ulClass' => 'am-tabs',
        'activeClass' => 'active',
        'normalClass' => 'normal',
        'disabledClass' => 'disabled',
        'maxDepth' => 1,
    )
);
?>
</div>